baseURL = "https://example.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-zealoft"

[params]
  version = "1.0.0"
  themeColor = "#FFFFFF"

[params.author]
  hello_line = "Hello, I'm Jim Zenn."
  hello_subline = "Software engineer. I do graphic design for fun."
  hello_p = """
  he / him. <br>
  Lives in Menlo Park, California. <br>
  <br>
  Also known as 曾庆伟.
  """
